-- MySQL Script generated by MySQL Workbench
-- Sat Apr  5 14:41:48 2014
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema uwsn_viewer
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `uwsn_viewer` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `uwsn_viewer` ;

-- -----------------------------------------------------
-- Table `uwsn_viewer`.`NodeNetwork`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `uwsn_viewer`.`NodeNetwork` (
  `NetworkId` INT NOT NULL AUTO_INCREMENT ,
  `Name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`NetworkId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uwsn_viewer`.`Node`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `uwsn_viewer`.`Node` (
  `NodeId` INT NOT NULL AUTO_INCREMENT,
  `NetworkId` INT NOT NULL,
  `Name` VARCHAR(100) NOT NULL,
  `Latitude` FLOAT(10,6) NOT NULL,
  `Longitude` FLOAT(10,6) NOT NULL,
  `Altitude` FLOAT(10,6) NOT NULL,
  PRIMARY KEY (`NodeId`),
  INDEX `FK_NetworkID_idx` (`NetworkId` ASC),
  CONSTRAINT `FK_NetworkID`
    FOREIGN KEY (`NetworkId`)
    REFERENCES `uwsn_viewer`.`NodeNetwork` (`NetworkId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
